const AUTH_USER = 'AUTH_USER';
const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
const AUTH_ERROR = 'AUTH_ERROR';
const BUSINESS_SERVICE_URI = 'https://secure-dawn-46321.herokuapp.com/api/v1.0';
const ADD_ITEM = 'ADD_ITEM';
const EDIT_ITEM = 'EDIT_ITEM'

export { AUTH_USER, AUTH_ERROR, AUTH_SIGNOUT,BUSINESS_SERVICE_URI,ADD_ITEM,EDIT_ITEM }